#!/bin/sh
module=aesdchar
device=aesdchar
mode="664"
echo "Loading aesdchar module - datoteka"

# Group: since distributions do it differently, look for wheel or use staff
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi


echo "Loading local built file ${module}"
modprobe $module $* || exit 1

major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
rm -f /dev/${device}
mknod /dev/${device} c $major 0
chgrp $group /dev/${device}
chmod $mode  /dev/${device}
